---
title: "Infographic"
author: "Helena Parsons"
date: "2026-05-27"
format: pdf
---

# 1: Loading packages
```{r}
#| label: loading-packages
#| warning: false
library(tidyverse)
library(readxl)
library(ggplot2)
library(ggridges)
library(here)
library(corrplot)
library(rstatix)
library(ggeffects)
```

# 2: Visualizations

## 2a. Reading in data
```{r}
#| label: object-for-data

job_search <- read_csv(here("data", "personal-data.csv"))
```

## 2b. Scatterplot for outside engagements

```{r}
#| label: first-visualization

ggplot(data = job_search,
                        mapping = aes(x = outside_eng,
                                      y = job_search)) +
  geom_point(color = "turquoise4",
              size = 3) +
  labs(title = "Affect of outside engagements on job search",
       x = "Time spent at work or school (hours)",
       y = "Time spent on job search (min)") + 
  theme_linedraw() +
  theme(panel.grid.major = element_blank(),
         panel.grid.minor = element_blank())
```

## 2c. Ridgeline graph for stress

```{r}
job_search_clean <- job_search |>
  mutate(stress = case_when (
    stress == "0" ~ "Zero",
    stress == "1" ~ "One",
    stress == "2" ~ "Two",
    stress == "3" ~ "Three",
    stress == "4" ~ "Four",
    stress == "5" ~ "Five"))
```


```{r}

ggplot(data = job_search_clean,
       mapping = aes(x = job_search,
                     y = stress)) +
  geom_density_ridges_gradient(color = "darkslategray4",
                               fill = "darkslategray3") +
  labs(title = "Job search differs by level of stress",
       x = "Time spent on job search (minutes)",
       y = "Level of stress"
       ) +
  theme_linedraw() +
  theme(panel.grid.major = element_blank(),
         panel.grid.minor = element_blank())
```

## 2d. Correlogram

```{r}
job_search_corr <- job_search |>
  select(job_search, outside_eng, stress, sleep, social_media, day_to_grad)
```

```{r}

corrplot(cor(job_search))
```

